spring:

  application:
    name: BackEnd_Server

  config:
    import: "optional:file:.env[.properties]"

  datasource:
    url: jdbc:mariadb://${DB_URL:localhost:3306}/sejongclass
    username: root
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
